config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  #get 'home/index'
  root 'home#index' # to make it root, use '#'
  get 'home/about'

  post "/" => 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_31d2290eac384fa597b270b0e49ab050')

    if params[:ticker] == ''
      @nothing = "Hey! You forgot to Enter A Symbol"
      puts "========== Controller, " + @nothing
    elsif (params[:ticker])
      begin
        @stock = StockQuote::Stock.quote(params[:ticker])
        @url = StockQuote::Stock.logo(params[:ticker]).url

        puts "========== Controller, found = " + @stock.company_name + "=========="
      rescue
        @error = "Hey! That Stock Symbol Doesn't Exist"  
        puts "========== Controller, " + @error
      end
    else
      puts "========== Controller,,,,"
    end
    
  end

  def about
  
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
</br>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissable" role="alert">
      <button class="close" data-dismiss="alert">
        <small><sup>x</sup></small>
      </button>
      <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_footer.html.erb
</br>
</br>

<center> Copyrights to Heejun </center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid ">
    <!--a class="navbar-brand" href="#">Stock</a-->
    <%= link_to "Root", root_path, class:"navbar-brand text-light"  %> 

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 " >
        
        <li class="nav-item ">
          <%= link_to "About", home_about_path, class: "nav-link text-light" %>
          <!--a class="nav-link" href="#">Link</a-->
        </li>

        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link text-light" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Show Stocks", stocks_path, class: "nav-link text-light" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Add Stocks", new_stock_path, class: "nav-link text-light" %>
          </li>
          
          <li class="nav-item" >
            <%#= link_to "LogOut", destroy_user_session_path, :method => :delete, :data => { :no_turbolink => true },class: "nav-link text-light"%>
            <%= button_to "LogOut", destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-light" %>
          </li>
          
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-light" %>
          </li>

        <%end>%>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>

  </div>
</nav>

app/views/home/about.html.erb
<h1>About Freshlit</h1>
<p> Hello. My name is Heejun </p>

<!--p>Find me in app/views/home/about.html.erb</p-->

app/views/home/index.html.erb
<h1>Providentia</h1>
<!--p> Hello! This is my First Rails App </p-->

<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
    <%= submit_tag 'Lookup', data: { turbo: false } %>
<% end %>

<% if @stock %>
    <% puts "========== Index, Value = " + @stock.company_name + "==========" %>
    <img src = "<%= @url%>"> </br>
    Name  : <%= @stock.company_name %> </br>
    Price : <%= @stock.latest_price %>
<% elsif @nothing %>
    <% puts "========== Index, Params is NULL ==========\n" + @nothing %>
    <%= @nothing %>
<% else %>
    <% puts "========== Index, no @stock ==========" %>
<% end %>

<% if @error %>
    <% puts "========== Index, error ==========\n" + @error %>
    <%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Providentia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!--link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"-->
  </head>

  <body>
    <%= render 'home/navbar' %>
    
    <div class="container">
      <%= render 'home/flash' %>

      </br>
      <%= yield %>
      </br>
    </div>

    <%= render 'home/footer' %>

    <!--script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script-->
  </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock) do |form| %>
  <% if stock.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ticker, style: "display: block" %>
    <%= form.text_field :ticker %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>">
<table class="table">
  <tbody>
    <tr>
      <% if stock.ticker == '' %>%
        <% @nothing = "Nothing" %>
        <% puts "========== stock.html, " + @nothing  %>
      <% elsif (stock.ticker) %>
        <% begin %>
          <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
          <td><%= @ticker.company_name %></td>
          <td><%= @ticker.symbol %></td>
          <td><%= number_with_precision( @ticker.latest_price, :pricision => 2, :delimiter => ',' )%></td>
          <td><p><%= link_to "Show this stock", stock %></p></td>

          <% puts "========== stock.html, found = " + @ticker.company_name + "==========" %>
        <% rescue  %>
          <% @error = "Error"   %>
          <% puts "========== stock.html, " + @error %>
        <% end %>
      <% else %>
        <% puts "========== stock.html,,,," %>
      <% end %>
    </tr>
  </tbody>
</table>
</div>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Show this stock", @stock %> |
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<div id="stocks">
<table class="table">
  <thead>
    <tr>
      <th> company </th>
      <th> Ticker </th>
      <th> Current Price </th>
      <th> Link </th>
  </thead>
  </table>
  <% @stocks.each do |stock| %>
    <% if stock.user_id == current_user.id %>

      <% if stock.ticker == '' %>%
        <% @nothing = "Nothing" %>
        <% puts "========== Controller, " + @nothing  %>
        
      <% elsif (stock.ticker) %>
        <% begin %>
          <% @ticker = StockQuote::Stock.quote(stock.ticker) %>
       
          <%= render stock %>

          <% puts "========== Controller, found = " + @ticker.company_name + "==========" %>
        <% rescue  %>
          <% @error = "Error"   %>
          <% puts "========== Controller, " + @error %>
        <% end %>
      <% else %>
        <% puts "========== Controller,,,," %>
      <% end %>

    <% end %>
  <% end %>
</div>

<%= link_to "New stock", new_stock_path %>


</br></br>

<%@num = 1%>
  <% @stocks.each do |te|%>
     <%= @num %> <%= te.ticker %> <%= te.user_id %> </br>
     <% @num += 1 %>
<% end %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render "form", stock: @stock %>

<br>

<div>
  <%= link_to "Back to stocks", stocks_path %>
</div>

app/views/stocks/show.html.erb
<%= render @stock %>

<div>
  <%= link_to "Edit this stock", edit_stock_path(@stock) %> |
  <%= link_to "Back to stocks", stocks_path %>

  <%= button_to "Destroy this stock", @stock, method: :delete %>
</div>